name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ secrets.gcpProjectId }}
          service_account_email: ${{ secrets.gcpSaEmail }}
          service_account_key: ${{ secrets.gcpSaKey }}
          export_default_credentials: true
      - run: gcloud info
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm start
        env:
          ROAM_EMAIL: ${{ secrets.roamEmail }}
          ROAM_PASSWORD: ${{ secrets.roamPassword }}
          AWS_BUCKET_NAME: ${{ secrets.awsBucketName }}
          AWS_ACCESS_KEY_ID: ${{ secrets.awsAccessKeyId }}
          AWS_ACCESS_KEY_SECRET: ${{ secrets.awsAccessKeySecret }}
          GCS_BUCKET_NAME: ${{ secrets.gcsBucketName }}
          STORAGE_OPT: ${{ secrets.storageOpt }}
